package com.gui;

import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * 
 * @author Tim
 */
public class Logger extends javax.swing.JPanel implements Runnable {
	Format formatter;
	private long startTime;
	Thread Xeq;

	/** Creates new form Logger */
	public Logger() {
		initComponents();
		startTime = System.currentTimeMillis();
		start();
	}

	public void start() {
		if (Xeq == null) {
			Xeq = new Thread(this);
			Xeq.start();
		}
	}

	public void addToLog(String s) {
		Date date = new Date();
		formatter = new SimpleDateFormat("hh:mm:ss a");
		String t = formatter.format(date);
		logPane.setText(logPane.getText() + "\n" + s + " - " + t);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		logPane = new javax.swing.JTextPane();
		jLabel2 = new javax.swing.JLabel();

		jLabel1.setText("Time Played: ");

		logPane.setBorder(javax.swing.BorderFactory.createCompoundBorder());
		logPane.setText("Welcome to Solas");
		jScrollPane1.setViewportView(logPane);

		jLabel2.setText("Info");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 245,
						Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(79, 79, 79)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addComponent(
																		jLabel2))
												.addComponent(jLabel1))
								.addContainerGap(102, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel2)
								.addGap(27, 27, 27)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										362, Short.MAX_VALUE)));
	}// </editor-fold>
		// Variables declaration - do not modify

	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextPane logPane;

	// End of variables declaration
	@Override
	public void run() {
		while (true) {
			long s = (System.currentTimeMillis() - startTime)/1000;
			jLabel1.setText(String.format("%d:%02d:%02d", s / 3600,
					(s % 3600) / 60, (s % 60)));
			try {
				Thread.sleep(900);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
}
